### ISSUE TITLE
[feat]: switching to Bearer authorization

### ISSUE THREAD

**Issue by mikayelgr** [getpolygon/polygon#18]
To make Polygon even more secure and improve the quality and the architecture of code, authentication system will have to be redesigned using a Bearer token.

By doing this we will also ensure that the API is easily debuggable and more accessible by applications such as Postman.

Info:

- RFC spec: https://datatracker.ietf.org/doc/html/rfc6750
- Shorter RFC specification with better formatting https://github.com/michaelgrigoryan25/rfc6750

**Comment by mikayelgr** [comment]
Bearer token authorization implementation for the API has started from 3993bfd23a784543c1c7da4eb0874e800243cc59 commit

**Comment by nobalpha** [comment]
Hey @michaelgrigoryan25 !

Have you managed switching fully to Bearer authentication? 

Is there anything I can help on?

**Comment by mikayelgr** [comment]
Hey @nobalpha 👋

Thank you very much for being interested in helping the further development of Polygon, I really appreciate it 🙂

> Have you managed switching fully to Bearer authentication?

Not yet 😅. I just started implementing Bearer authentication on `feature_bearer-auth` branch.

> Is there anything I can help on?

Yup! There are some things that I need help with. I will update you as soon as I get home!

Thanks!

**Comment by mikayelgr** [comment]
Hi again, @nobalpha.

Here are some things that need to be done to the authentication system:

- **Forbid** the access to authentication routes(`/auth/login`, `/auth/register`) _**if**_ the user is **_already authenticated_**. I'm thinking of maybe sending a cookie to the user after login so that we can use that cookie to check whether we should give access to that endpoint or not. **The only thing** that makes me back away from this option is the fact of having 2 let's say authentication "tokens" that we will need to keep track of.
- [**`register.ts`**](https://github.com/polygon-isecure/core/blob/nightly--sql_version/src/controllers/auth/register.ts) and [**`verify.ts`**](https://github.com/polygon-isecure/core/blob/nightly--sql_version/src/controllers/auth/verify.ts) should be grouped under one folder to improve the project structure of the code, since `/verify` endpoint is nested under `/auth/register`(final result **_`/auth/register/verify/:token`_**).
- In [**`authenticate.ts`**](https://github.com/polygon-isecure/core/blob/nightly--sql_version/src/middleware/authenticate.ts) lines **`19-27`** I do not know whether I should be checking whether the user exists or not. This will have to be investigated further.

There are some other things but these are the most essential ones.

Thanks,

Michael.

**Comment by nobalpha** [comment]
Hey @michaelgrigoryan25 !

I'm sorry for the late response, I couldn't return to you.

Ahm, I understood your needs and I'm ready to help them, but the thing is I couldn't really setup the project as I'm not really experienced enough to use PostgreSQL and Redis. 

If it's OK, I can make an external authentication system and try to adapt it into the project. 

What do you think?

**Comment by mikayelgr** [comment]
Hi @nobalpha 

> I'm sorry for the late response, I couldn't return to you.

No worries.

> If it's OK, I can make an external authentication system and try to adapt it into the project.

Could you please elaborate a bit here? What do you mean by **external**?

**Comment by nobalpha** [comment]
I mean, creating an authantication elsewhere - to tackle the dependencies and their configuration -, then if I get something working, integrating it to the present project structure. 

In short, there are loads of errors :D which corrupts my work :/

Instead of trying to run the whole codebase, I'll implement the auth mechanism externally.

**Comment by mikayelgr** [comment]
Ah yeah, sure! For a second I though that you wanted to integrate something like Auth0 or Okta(with which I did not want to work). But yeah, you can try to work on an implementation externally. There are no issues w/ that. Thanks

**Comment by mikayelgr** [comment]
And by the way, if you are interested in chatting with the community you can join our Discord server at https://discord.com/invite/tExw2XqgtU

**Comment by mikayelgr** [comment]
Mostly implemented
